# Generated by Django 5.2.1 on 2025-05-21 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('idAlternativa', models.AutoField(primary_key=True, serialize=False)),
                ('alternativa', models.CharField(max_length=250)),
                ('puntajeObtenido', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('idDificultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDiff', models.CharField(max_length=50)),
                ('descDiff', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEspecialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoFinal',
            fields=[
                ('idEstadoFinal', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstadoFinal', models.CharField(max_length=50)),
                ('descEstadoFinal', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('idFoto', models.AutoField(primary_key=True, serialize=False)),
                ('pfp', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
                ('puntajeTotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AlternativaSeleccionada',
            fields=[
                ('idRespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistroRespuesta', models.DateField()),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alternativa')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('idModulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreModulo', models.CharField(max_length=50)),
                ('dif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dificultad')),
                ('espe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='alternativa',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pregunta'),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('idTema', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTema', models.CharField(max_length=100)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='api.tema'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUniqueUser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=50)),
                ('isAdmin', models.BooleanField(default=False)),
                ('fotoPerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fotoperfil')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentajeCompletado', models.FloatField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('puntajeObtenido', models.IntegerField()),
                ('estadoFinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estadofinal')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
