# Generated by Django 5.2.1 on 2025-06-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='valor',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='multiplicador',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tema',
            name='puntosTotal',
            field=models.IntegerField(default=0),
        ),
    ]
