# Generated by Django 5.2.1 on 2025-06-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_cargo_alter_usuario_fechacontratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaContratacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
