# Generated by Django 5.2.1 on 2025-06-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pregunta_valor_evaluacion_multiplicador_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
