# Generated by Django 5.2.1 on 2025-06-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoperfil',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
