# Generated by Django 5.2.1 on 2025-06-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_fechacontratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='ronda',
            field=models.IntegerField(default=1),
        ),
    ]
