# Generated by Django 5.2.1 on 2025-06-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_progreso_ronda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='porcentajeCompletado',
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='puntajeObtenido',
        ),
    ]
