# Generated by Django 5.2.1 on 2025-06-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_progreso_porcentajecompletado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
